### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by Lassulus** [NixOS/nixpkgs-merge-bot#30]
```
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]: ERROR:root:internal error
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]: Traceback (most recent call last):
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:   File "/nix/store/i3f32bcbq1731al8p521rcmbvcdqn81n-nixpkgs-merge-bot/lib/python3.11/site-packages/nixpkgs_merge_bot/github.py", line 90, in _request
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:     resp = urllib.request.urlopen(req)
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:   File "/nix/store/y027d3bvlaizbri04c1bzh28hqd6lj01-python3-3.11.7/lib/python3.11/urllib/request.py", line 216, in urlopen
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:     return opener.open(url, data, timeout)
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:   File "/nix/store/y027d3bvlaizbri04c1bzh28hqd6lj01-python3-3.11.7/lib/python3.11/urllib/request.py", line 525, in open
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:     response = meth(req, response)
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:                ^^^^^^^^^^^^^^^^^^^
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:   File "/nix/store/y027d3bvlaizbri04c1bzh28hqd6lj01-python3-3.11.7/lib/python3.11/urllib/request.py", line 634, in http_response
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:     response = self.parent.error(
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:                ^^^^^^^^^^^^^^^^^^
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:   File "/nix/store/y027d3bvlaizbri04c1bzh28hqd6lj01-python3-3.11.7/lib/python3.11/urllib/request.py", line 563, in error
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:     return self._call_chain(*args)
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:            ^^^^^^^^^^^^^^^^^^^^^^^
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:   File "/nix/store/y027d3bvlaizbri04c1bzh28hqd6lj01-python3-3.11.7/lib/python3.11/urllib/request.py", line 496, in _call_chain
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:     result = func(*args)
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:              ^^^^^^^^^^^
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:   File "/nix/store/y027d3bvlaizbri04c1bzh28hqd6lj01-python3-3.11.7/lib/python3.11/urllib/request.py", line 643, in http_error_default
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:     raise HTTPError(req.full_url, code, msg, hdrs, fp)
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]: urllib.error.HTTPError: HTTP Error 403: Forbidden
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]: The above exception was the direct cause of the following exception:
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]: Traceback (most recent call last):
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:   File "/nix/store/i3f32bcbq1731al8p521rcmbvcdqn81n-nixpkgs-merge-bot/lib/python3.11/site-packages/nixpkgs_merge_bot/webhook/handler.py", line 84, in do_POST
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:     self.process_event(body)
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:   File "/nix/store/i3f32bcbq1731al8p521rcmbvcdqn81n-nixpkgs-merge-bot/lib/python3.11/site-packages/nixpkgs_merge_bot/webhook/handler.py", line 58, in process_event
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:     resp = handler(payload, self.settings)
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:   File "/nix/store/i3f32bcbq1731al8p521rcmbvcdqn81n-nixpkgs-merge-bot/lib/python3.11/site-packages/nixpkgs_merge_bot/webhook/issue_comment.py", line 73, in issue_comment
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:     client.create_issue_reaction(
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:   File "/nix/store/i3f32bcbq1731al8p521rcmbvcdqn81n-nixpkgs-merge-bot/lib/python3.11/site-packages/nixpkgs_merge_bot/github.py", line 128, in create_issue_reaction
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:     return self.post(
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:            ^^^^^^^^^^
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:   File "/nix/store/i3f32bcbq1731al8p521rcmbvcdqn81n-nixpkgs-merge-bot/lib/python3.11/site-packages/nixpkgs_merge_bot/github.py", line 104, in post
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:     return self._request(path, "POST", data)
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:   File "/nix/store/i3f32bcbq1731al8p521rcmbvcdqn81n-nixpkgs-merge-bot/lib/python3.11/site-packages/nixpkgs_merge_bot/github.py", line 97, in _request
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:     raise GithubClientError(e.code, e.reason, url, resp_body) from e
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]: nixpkgs_merge_bot.github.GithubClientError: (403, 'Forbidden', 'https://api.github.com/repos/NixOS/nixpkgs/issues/comments/1945485836/reactions', '{"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/reactions/reactions#create-reaction-for-an-issue-comment"}')
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:  - - [15/Feb/2024 07:13:18] code 500, message Internal Server Error
Feb 15 07:13:18 nixpkgs-merge-bot cvrp9hwwl2mx1kys45004y9isvbv5ly7-nixpkgs-merge-bot[1647506]:  - - [15/Feb/2024 07:13:18] "POST / HTTP/1.1" 500 -
```

**Comment by Lassulus** [comment]
It seems our token doesn't have enough permissions to write answers anymore

**Comment by Lassulus** [comment]
this seems to be fixed now
